import type { Metadata } from "next";
import { Geist, Geist_Mono, Bitcount_Grid_Single } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const bitcountGridSingle = Bitcount_Grid_Single({
    variable: "--font-bitcount-grid-single",
    subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${bitcountGridSingle.variable}`}>
        {children}
      </body>
    </html>
  );
}
